# generated by datamodel-codegen:
#   filename:  manifest.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Http(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed_hosts: Annotated[
        list[str] | None,
        Field(description="Allowed hostnames. Empty array allows all hosts."),
    ] = None


class Ai(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    models: Annotated[
        list[str] | None,
        Field(description="Allowed model names. Empty array allows all models."),
    ] = None


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http: Annotated[Http | None, Field(description="HTTP request capability.")] = None
    ai: Annotated[Ai | None, Field(description="AI model access capability.")] = None


class Asset(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[str, Field(pattern="^(?!/)(?!.*\\.\\.).+$")]


class Scope(Enum):
    activity = "activity"
    course = "course"
    global_ = "global"
    user_activity = "user,activity"
    user_course = "user,course"
    user_global = "user,global"


class FieldBase(BaseModel):
    scope: Annotated[
        Scope,
        Field(
            description="Scope of the field. Scopes without 'user' are shared across users. 'activity' scopes are per-activity-instance, 'course' scopes are per-course, 'global' scopes are for the whole platform."
        ),
    ]
    default: Annotated[
        Any | None, Field(description="Default value (must match declared type).")
    ] = None


class IntegerType(BaseModel):
    type: Literal["integer"]


class NumberType(BaseModel):
    type: Literal["number"]


class StringType(BaseModel):
    type: Literal["string"]


class BooleanType(BaseModel):
    type: Literal["boolean"]


class IntegerField(IntegerType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class NumberField(NumberType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class StringField(StringType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class BooleanField(BooleanType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class XplaActivityManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    name: Annotated[str, Field(description="Unique identifier for the activity.")]
    client: Annotated[
        str,
        Field(
            description="Path to the client-side JavaScript file, relative to activity directory.",
            pattern="^(?!/)(?!.*\\.\\.).+$",
        ),
    ]
    server: Annotated[
        str | None,
        Field(
            description="Path to the server-side WASM file, relative to activity directory.",
            pattern="^(?!/)(?!.*\\.\\.).+$",
        ),
    ] = None
    capabilities: Annotated[
        Capabilities | None,
        Field(description="Declared capabilities that the sandbox can use."),
    ] = None
    fields: Annotated[
        dict[str, FieldDefinition] | None,
        Field(description="Declared activity fields with type and scope."),
    ] = None
    actions: Annotated[
        dict[str, TypeSchema] | None,
        Field(description="Actions the client can send to the server sandbox."),
    ] = None
    events: Annotated[
        dict[str, TypeSchema] | None,
        Field(description="Events the server sandbox can emit to the client."),
    ] = None
    assets: Annotated[
        list[Asset] | None,
        Field(
            description="Static file paths that can be served as assets. Must be relative (no leading '/') and cannot contain '..'."
        ),
    ] = None


class ArrayType(BaseModel):
    type: Literal["array"]
    items: TypeSchema


class ObjectType(BaseModel):
    type: Literal["object"]
    properties: dict[str, TypeSchema]


class LogType(BaseModel):
    type: Literal["log"]
    items: TypeSchema


class ArrayField(ArrayType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class ObjectField(ObjectType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class TypeSchema(
    RootModel[
        IntegerType | NumberType | StringType | BooleanType | ArrayType | ObjectType
    ]
):
    root: IntegerType | NumberType | StringType | BooleanType | ArrayType | ObjectType


class LogField(LogType, FieldBase):
    model_config = ConfigDict(
        extra="forbid",
    )


class FieldDefinition(
    RootModel[
        IntegerField
        | NumberField
        | StringField
        | BooleanField
        | ArrayField
        | ObjectField
        | LogField
    ]
):
    root: (
        IntegerField
        | NumberField
        | StringField
        | BooleanField
        | ArrayField
        | ObjectField
        | LogField
    )


XplaActivityManifest.model_rebuild()
ArrayType.model_rebuild()
ObjectType.model_rebuild()
LogType.model_rebuild()
ArrayField.model_rebuild()
ObjectField.model_rebuild()
LogField.model_rebuild()
