"""Initial model creation

Revision ID: 0001
Revises:
Create Date: 2026-04-10 11:40:47.949342
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fieldentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "activity_name", "activity_id", "user_id", "key"
        ),
    )
    with op.batch_alter_table("fieldentry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fieldentry_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fieldentry_activity_name"), ["activity_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fieldentry_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fieldentry_key"), ["key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_fieldentry_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "fieldlogentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "activity_name", "activity_id", "user_id", "key", "entry_id"
        ),
    )
    with op.batch_alter_table("fieldlogentry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fieldlogentry_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fieldlogentry_activity_name"),
            ["activity_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fieldlogentry_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fieldlogentry_key"), ["key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_fieldlogentry_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "fieldlogseq",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("next_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "activity_name", "activity_id", "user_id", "key"
        ),
    )
    with op.batch_alter_table("fieldlogseq", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fieldlogseq_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fieldlogseq_activity_name"), ["activity_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fieldlogseq_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fieldlogseq_key"), ["key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_fieldlogseq_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "course",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "usersession",
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("usersession", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usersession_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "courseactivity",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "page",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pageactivity",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["page.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pageactivity")
    op.drop_table("page")
    op.drop_table("courseactivity")
    with op.batch_alter_table("usersession", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usersession_user_id"))

    op.drop_table("usersession")
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_owner_id"))

    op.drop_table("course")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("fieldlogseq", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fieldlogseq_user_id"))
        batch_op.drop_index(batch_op.f("ix_fieldlogseq_key"))
        batch_op.drop_index(batch_op.f("ix_fieldlogseq_course_id"))
        batch_op.drop_index(batch_op.f("ix_fieldlogseq_activity_name"))
        batch_op.drop_index(batch_op.f("ix_fieldlogseq_activity_id"))

    op.drop_table("fieldlogseq")
    with op.batch_alter_table("fieldlogentry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fieldlogentry_user_id"))
        batch_op.drop_index(batch_op.f("ix_fieldlogentry_key"))
        batch_op.drop_index(batch_op.f("ix_fieldlogentry_course_id"))
        batch_op.drop_index(batch_op.f("ix_fieldlogentry_activity_name"))
        batch_op.drop_index(batch_op.f("ix_fieldlogentry_activity_id"))

    op.drop_table("fieldlogentry")
    with op.batch_alter_table("fieldentry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fieldentry_user_id"))
        batch_op.drop_index(batch_op.f("ix_fieldentry_key"))
        batch_op.drop_index(batch_op.f("ix_fieldentry_course_id"))
        batch_op.drop_index(batch_op.f("ix_fieldentry_activity_name"))
        batch_op.drop_index(batch_op.f("ix_fieldentry_activity_id"))

    op.drop_table("fieldentry")
    # ### end Alembic commands ###
