# generated by datamodel-codegen:
#   filename:  manifest.schema.json
#   timestamp: 2026-02-11T17:40:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints


class Http(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed_hosts: list[str] | None = Field(
        None, description="Allowed hostnames. Empty array allows all hosts."
    )


class Ai(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[str] | None = Field(
        None, description="Allowed model names. Empty array allows all models."
    )


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http: Http | None = Field(None, description="HTTP request capability.")
    ai: Ai | None = Field(None, description="AI model access capability.")


class Type(Enum):
    integer = "integer"
    number = "number"
    string = "string"
    boolean = "boolean"
    array = "array"
    object = "object"


class Scope(Enum):
    unit = "unit"
    user_unit = "user,unit"


class TypeSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(..., description="Data type.")
    items: TypeSchema | None = Field(None, description="Schema for array items.")
    properties: dict[str, TypeSchema] | None = Field(
        None, description="Schema for object properties."
    )


class ValueDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(
        ..., description="Data type of the value. Uses JSON Schema type names."
    )
    items: TypeSchema | None = Field(
        None, description="Schema for array items. Required when type is 'array'."
    )
    properties: dict[str, TypeSchema] | None = Field(
        None, description="Schema for object properties. Used when type is 'object'."
    )
    scope: Scope = Field(
        ...,
        description="Scope of the value. 'unit' is shared across users, 'user,unit' is per-user.",
    )
    default: Any | None = Field(
        None, description="Default value (must match declared type)."
    )


class GulpsActivityManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    name: str = Field(..., description="Unique identifier for the activity.")
    client: str = Field(
        ...,
        description="Path to the client-side JavaScript file, relative to activity directory.",
    )
    server: str | None = Field(
        None,
        description="Path to the server-side WASM file, relative to activity directory.",
    )
    capabilities: Capabilities | None = Field(
        None, description="Declared capabilities that the sandbox can use."
    )
    values: dict[str, ValueDefinition] | None = Field(
        None, description="Declared activity values with type and scope."
    )
    actions: dict[str, TypeSchema] | None = Field(
        None, description="Actions the client can send to the server sandbox."
    )
    events: dict[str, TypeSchema] | None = Field(
        None,
        description="Events the server sandbox can emit to the client. values.change.* events are implicit.",
    )
    static: (
        list[Annotated[str, StringConstraints(pattern=r"^(?!/)(?!.*\.\.).+$")]] | None
    ) = Field(
        None,
        description="Static file paths that can be served as assets. Must be relative (no leading '/') and cannot contain '..'.",
    )


TypeSchema.model_rebuild()
