# generated by datamodel-codegen:
#   filename:  manifest.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Http(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed_hosts: Annotated[
        list[str] | None,
        Field(description="Allowed hostnames. Empty array allows all hosts."),
    ] = None


class Ai(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    models: Annotated[
        list[str] | None,
        Field(description="Allowed model names. Empty array allows all models."),
    ] = None


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http: Annotated[Http | None, Field(description="HTTP request capability.")] = None
    ai: Annotated[Ai | None, Field(description="AI model access capability.")] = None


class StaticItem(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[str, Field(pattern="^(?!/)(?!.*\\.\\.).+$")]


class Type(Enum):
    integer = "integer"
    number = "number"
    string = "string"
    boolean = "boolean"
    array = "array"
    object = "object"


class Scope(Enum):
    activity = "activity"
    course = "course"
    global_ = "global"
    user_activity = "user,activity"
    user_course = "user,course"
    user_global = "user,global"


class TypeSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Type, Field(description="Data type.")]
    items: Annotated[
        TypeSchema | None, Field(description="Schema for array items.")
    ] = None
    properties: Annotated[
        dict[str, TypeSchema] | None, Field(description="Schema for object properties.")
    ] = None


class FieldDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Type, Field(description="Data type of the field. Uses JSON Schema type names.")
    ]
    items: Annotated[
        TypeSchema | None,
        Field(description="Schema for array items. Required when type is 'array'."),
    ] = None
    properties: Annotated[
        dict[str, TypeSchema] | None,
        Field(description="Schema for object properties. Used when type is 'object'."),
    ] = None
    scope: Annotated[
        Scope,
        Field(
            description="Scope of the field. Scopes without 'user' are shared across users. 'activity' scopes are per-activity-instance, 'course' scopes are per-course, 'global' scopes are for the whole platform."
        ),
    ]
    default: Annotated[
        Any | None, Field(description="Default value (must match declared type).")
    ] = None


class XplaActivityManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    name: Annotated[str, Field(description="Unique identifier for the activity.")]
    client: Annotated[
        str,
        Field(
            description="Path to the client-side JavaScript file, relative to activity directory.",
            pattern="^(?!/)(?!.*\\.\\.).+$",
        ),
    ]
    server: Annotated[
        str | None,
        Field(
            description="Path to the server-side WASM file, relative to activity directory.",
            pattern="^(?!/)(?!.*\\.\\.).+$",
        ),
    ] = None
    capabilities: Annotated[
        Capabilities | None,
        Field(description="Declared capabilities that the sandbox can use."),
    ] = None
    fields: Annotated[
        dict[str, FieldDefinition] | None,
        Field(description="Declared activity fields with type and scope."),
    ] = None
    actions: Annotated[
        dict[str, TypeSchema] | None,
        Field(description="Actions the client can send to the server sandbox."),
    ] = None
    events: Annotated[
        dict[str, TypeSchema] | None,
        Field(description="Events the server sandbox can emit to the client."),
    ] = None
    static: Annotated[
        list[StaticItem] | None,
        Field(
            description="Static file paths that can be served as assets. Must be relative (no leading '/') and cannot contain '..'."
        ),
    ] = None


TypeSchema.model_rebuild()
