# generated by datamodel-codegen:
#   filename:  manifest.schema.json
#   timestamp: 2026-02-06T05:51:08+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Http(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed_hosts: list[str] | None = Field(
        None, description="Allowed hostnames. Empty array allows all hosts."
    )


class Ai(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[str] | None = Field(
        None, description="Allowed model names. Empty array allows all models."
    )


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http: Http | None = Field(None, description="HTTP request capability.")
    ai: Ai | None = Field(None, description="AI model access capability.")


class Type(Enum):
    integer = "integer"
    float = "float"
    string = "string"
    boolean = "boolean"


class Scope(Enum):
    unit = "unit"
    user_unit = "user,unit"


class Access(Enum):
    user = "user"
    unit = "unit"
    course = "course"
    platform = "platform"


class ValueDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(..., description="Data type of the value.")
    scope: Scope = Field(
        ...,
        description="Scope of the value. 'unit' is shared across users, 'user,unit' is per-user.",
    )
    access: Access = Field(
        ..., description="Minimum access level required to read this value."
    )
    default: Any | None = Field(
        None, description="Default value (must match declared type)."
    )


class GulpsActivityManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Unique identifier for the activity.")
    client: str = Field(
        ...,
        description="Path to the client-side JavaScript file, relative to activity directory.",
    )
    server: str | None = Field(
        None,
        description="Path to the server-side WASM file, relative to activity directory.",
    )
    capabilities: Capabilities | None = Field(
        None, description="Declared capabilities that the sandbox can use."
    )
    values: dict[str, ValueDefinition] | None = Field(
        None,
        description="Declared activity values with type, scope, and access control.",
    )
