"""FieldStore protocol — abstract interface for field persistence."""

from typing import Any, Protocol

from xpla.fields import FieldType


class FieldStore(Protocol):
    """Protocol for storing scalar and log field data."""

    # Scalar fields
    def get(self, key: str) -> FieldType | None: ...
    def set(self, key: str, value: FieldType) -> None: ...
    def delete(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...

    # Log fields
    def log_get(self, key: str, entry_id: int) -> FieldType | None: ...
    def log_get_range(
        self, key: str, from_id: int, to_id: int
    ) -> list[dict[str, Any]]: ...
    def log_append(self, key: str, value: FieldType) -> int: ...
    def log_delete(self, key: str, entry_id: int) -> bool: ...
    def log_delete_range(self, key: str, from_id: int, to_id: int) -> int: ...
